#!/bin/sh

png=`mktemp --tmpdir haxtestgfx.XXXXXXXX`

hax gfx11 $HAXTESTDIR/d1.drawlist 500 500 $png
md5sum $png | cut -b-32
rm -f $png

hax gfx11 $HAXTESTDIR/d2.drawlist 500 500 $png
md5sum $png | cut -b-32
rm -f $png

hax gfx11 $HAXTESTDIR/d3.drawlist 500 500 $png
md5sum $png | cut -b-32
rm -f $png
